pipeline {
    agent any

    environment {
        CONTAINER_NAME = 'bus-reservation-container'
        IMAGE_NAME = 'bus-reservation'
    }

    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/VENKY70325/bus-reservation-django.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("${IMAGE_NAME}", "myproject")
                }
            }
        }

        stage('Stop Old Containers') {
            steps {
                script {
                    // Stop previous container with the same name (if exists)
                    sh "docker rm -f ${CONTAINER_NAME} || true"
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    dockerImage.run(
                        "--name ${CONTAINER_NAME} " +
                        "-v ${env.WORKSPACE}/myproject/db.sqlite3:/app/db.sqlite3 " + // 🧠 persist DB!
                        "-p 8000:8000 " +
                        "/bin/sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'"
                    )
                }
            }
        }
    }
}
